#! /bin/sh

set -e

ln -sf /usr/share/supersonic/supersonic.sh /usr/bin/supersonic

chmod 750 /var/supersonic

# Clear jetty cache.
rm -rf /var/supersonic/jetty

# Configure Supersonic service.
update-rc.d supersonic defaults 99

# Start Supersonic service.
invoke-rc.d supersonic start
