#! /bin/sh

set -e

# Stop Supersonic service.
if [ -e /etc/init.d/supersonic ]; then
  invoke-rc.d supersonic stop
fi

# Backup database.
if [ -e /var/subsonic/db ]; then
  rm -rf /var/subsonic/db.backup
  cp -R /var/subsonic/db /var/subsonic/db.backup
fi

